name: Fullstack CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # CI-only MySQL credentials
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      # Backend connection credentials
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: app_db

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---- Backend (Spring Boot) ----
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
        working-directory: Backend

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build & Test backend
        working-directory: Backend
        run: ./mvnw clean verify
        env:
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_NAME: app_db

      # ---- Frontend (React + TypeScript) ----
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & Test Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          npm test -- --watchAll=false
